### ISSUE TITLE
JGrasp - Project

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#1]
No Project file exists.

**Comment by oliveje** [comment]
Is this a folder that needs to be added/created under the src folder labeled jGrasp Project or we grabbing the whole folder created by jGrasp when we setup the project and uploading? I saw this in the instructions which is why I loaded my Java file but was a little confused on exactly what was needed.

**Comment by oliveje** [comment]
I have added the jGrasp Project file - I figured out that I did not have my repo setup properly on GitHub Desktop. I was able to correct and once I did all the proper files moved to GitHub
