### ISSUE TITLE
UML - Class Diagram

### ISSUE THREAD

**Issue by jwood36** [oliveje/CIS255_Vehicle#3]
Once you build your Model Classes, observe what attributes are Instantiable (Customizable) and which are "Static" (value-based; Enum, Struct, etc.).  Construct appropriately each of these observed attributes.

**Comment by oliveje** [comment]
I am a little confused - Is this in reference to an issue with my initial class diagram or advice/guidance for the next task in detailing the design more? 
 
Just want to ensure I am understanding.

**Comment by oliveje** [comment]
i.	I initially had questions about the issue and was not able to get much support with my initial questions asked. I asked other students, but I am still not sure what I was doing wrong, so I am not sure if the issue is closed. I think the issue was I didn’t put Door, Engine, Color, Year in classes. I did redo the initial Visio to demonstrate this but I did have to modify the file name so I could upload the file – it is named Vehicle_UML_Basic
